\c message-system;

INSERT INTO "user" (id, username, password, display_name) VALUES (default, "andrey.koval@mail.ru", "simplePassword", "Andrey");
INSERT INTO "user" (id, username, password, display_name) VALUES (default, "mike.lohan@mail.ru", "J}]5uZxped{M+!Y.", "Mike");
INSERT INTO "user" (id, username, password, display_name) VALUES (default, "lee.doyle@mail.ru", "&?Sjn<274u&[8L`9", "Doyle");
INSERT INTO "user" (id, username, password, display_name) VALUES (default, "deborah.arnold@mail.ru", "hardPassword", "Arnold");
INSERT INTO "user" (id, username, password, display_name) VALUES (default, "lawrence.rosemarie@mail.ru", "z[<tJY;w6Mz@L'Au", "Lawrence");
INSERT INTO "user" (id, username, password, display_name) VALUES (default, "2mahmoud@highonline.store", "'/t9_`mnB<]Hp29s", "Ottavio");
INSERT INTO "user" (id, username, password, display_name) VALUES (default, "fjohnettez@topplayers.fun", "NW;~q.\JA&h3H4,R", "Zakariyya");
INSERT INTO "user" (id, username, password, display_name) VALUES (default, "1omar_s@zynga-email.com", "@8`?gMf~&,:Kp~X", "Elisabetta");
INSERT INTO "user" (id, username, password, display_name) VALUES (default, "3kelmendelby@newspro.fun", "8W@Td8AGb#W}SHq[", "Hudson");
INSERT INTO "user" (id, username, password, display_name) VALUES (default, "gss12348e@wpower.info", ":G#KYF3{8y}jAXFq", "Pal");
INSERT INTO "user" (id, username, password, display_name) VALUES (default, "thesham.57z@theglockneronline.com", "ZLVdD!'e9(Rhb", "Nobu");
INSERT INTO "user" (id, username, password, display_name) VALUES (default, "djasin.agushi1@paharpurmim.ga", "4S%XzjP?PhUV3UFw", "Franklyn");
INSERT INTO "user" (id, username, password, display_name) VALUES (default, "dmaggee@tsmc.mx", "td38BEVs-gTqmGSs", "Irena");
INSERT INTO "user" (id, username, password, display_name) VALUES (default, "4vivekvvsshuklav@aasgashashashajh.cf", "EXm?LP@^$HC4E+v3", "Nirmal");
INSERT INTO "user" (id, username, password, display_name) VALUES (default, "9hamd.ali.5249j@bestshopcoupon.net", "Y%8!?P9PruuNznj&", "Anna");
INSERT INTO "user" (id, username, password, display_name) VALUES (default, "wmohanadmano88v@d-link.cf", "Q9^8+PnEEUJh*=JN", "Walter");
INSERT INTO "user" (id, username, password, display_name) VALUES (default, "esou_sou_sisi4@mailw.info", "vuSYH?JYb2Z7E3bB", "Pari");
INSERT INTO "user" (id, username, password, display_name) VALUES (default, "fcecemanagerw@cheesepin.info", "b^54D6Qa^7LhVw9A", "Desmond");
INSERT INTO "user" (id, username, password, display_name) VALUES (default, "tfoued.rk.10@escanor99.com", "yZ5D3@RtnJH!6_#?", "Baltassar");
INSERT INTO "user" (id, username, password, display_name) VALUES (default, "3alexander@v-mail.xyz", "JnuU7qceS?rakaE9", "Viktor");
INSERT INTO "user" (id, username, password, display_name) VALUES (default, "isalma.chergui.9g@theodore1818.site", "Lj%z!9gxu?GJmyBy", "Ketil");
INSERT INTO "user" (id, username, password, display_name) VALUES (default, "7anaelkinganaanaz@mqg77378.ga", "pxx@9tybyV^_Z4W5", "Aristophanes");
INSERT INTO "user" (id, username, password, display_name) VALUES (default, "2ayoub@jaqueline1121.club", "rPw3Wp@%q5wN*cJM", "Livia");
INSERT INTO "user" (id, username, password, display_name) VALUES (default, "8simozakkaru@zeroknow.ga", "y_G7Z9?besrvQ&?!", "Benedetta");